openapi: 3.0.0
info:
  title: KZNDOT
  version: '1.0'
  description: >-
    The following is an API reference for the KZN DOT mobile application and
    backend. The document is designed to be a guide and documentation for the
    APIs.

































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































    Developers are expected to keep this document up to date and all changes that
    are made to the APIs and models need to be updated.
  contact:
    name: Mazi Muhlari
    email: mazim@boxfusion.co.za
servers:
  - url: 'http://kzndot.smartcitizen.com/api/v1'
  - url: 'http://testkzndot.smartcitizen.com/api/v1'
    description: ''
paths:
  /token:
    post:
      summary: Token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      description: Authenticate a user for access to the system. This request returns a new token.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples: {}
  /users/general:
    get:
      summary: General Information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  station:
                    type: string
                  region:
                    type: string
                  date:
                    type: string
                  nameOfOfficer:
                    type: string
                  rank:
                    type: string
                  officerInfrastructureNo:
                    type: string
      parameters:
        - schema:
            type: string
          in: header
          name: x-auth-token
          description: The authentication token
          required: true
      description: Retreive the general information about the officer such as their rank and station information.
    put:
      summary: General Information
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
          in: header
          name: x-auth-token
          description: The authentication token
          required: true
      description: Update the general information about the officer such as their rank and station information.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                station:
                  type: string
                region:
                  type: string
                date:
                  type: string
                nameOfOfficer:
                  type: string
                rank:
                  type: string
                officerInfrastructureNo:
                  type: string
  /tasks:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /accidents:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /incidents:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /checklists:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /transactions:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /stopandstarts:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /arrests:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /roadblocks:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /checklists/pre:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
  /checklists/post:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
components:
  schemas: {}
